# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nat_fastcore_wrappers", use_symbols = TRUE, package_name = "nat.fastcore")

#' @usage NULL
#' @useDynLib nat.fastcore, .registration = TRUE
NULL

#' Compute all distances to root.
#' @export
all_dists_to_root <- function(parents, sources, weights) .Call(wrap__all_dists_to_root, parents, sources, weights)

#' For each node ID in `parents` find its index in `nodes`.
#'
#' Importantly this is 0-indexed to match indexing in Rust.
#' Roots will have parent index -1.
#'
#' @export
node_indices <- function(nodes, parents) .Call(wrap__node_indices, nodes, parents)

#' Geodesic distances between nodes.
#' @export
geodesic_distances <- function(parents, sources, targets, weights, directed) .Call(wrap__geodesic_distances, parents, sources, targets, weights, directed)

#' Calculate Strahler Index.
#' @export
strahler_index <- function(parents, greedy, to_ignore, min_twig_size) .Call(wrap__strahler_index, parents, greedy, to_ignore, min_twig_size)

#' Connected components.
#' @export
connected_components <- function(parents) .Call(wrap__connected_components, parents)

#' Prune twigs below given threshold.
#'
#' Returns indices of nodes to keep.
#'
#' @export
prune_twigs <- function(parents, threshold, weights) .Call(wrap__prune_twigs, parents, threshold, weights)

#' Calculate child -> parent distances.
#' @export
child_to_parent_dists <- function(parents, x, y, z) .Call(wrap__child_to_parent_dists, parents, x, y, z)


# nolint end
