# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nat_fastcore_wrappers", use_symbols = TRUE, package_name = "nat.fastcore")

#' @usage NULL
#' @useDynLib nat.fastcore, .registration = TRUE
NULL

#' Compute all distances to root.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param sources Optional integer vector of node indices to measure from;
#'   `NULL` uses every node.
#' @param weights Optional numeric vector of child-to-parent edge weights;
#'   `NULL` counts edges (hop distance).
#' @return Numeric vector of distances to the root for each requested node.
#' @export
all_dists_to_root <- function(parents, sources, weights) .Call(wrap__all_dists_to_root, parents, sources, weights)

#' For each node ID in `parents` find its index in `nodes`.
#'
#' Importantly this is 0-indexed to match indexing in Rust.
#' Roots will have parent index -1.
#'
#' @param nodes Integer vector of node IDs.
#' @param parents Integer vector of parent IDs, one per node; roots use their
#'   own ID or a negative value.
#' @return Integer vector of 0-based parent indices (`-1` for roots).
#' @export
node_indices <- function(nodes, parents) .Call(wrap__node_indices, nodes, parents)

#' Geodesic distances between nodes.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param sources Optional integer vector of source node indices; `NULL` uses
#'   every node.
#' @param targets Optional integer vector of target node indices; `NULL` uses
#'   every node.
#' @param weights Optional numeric vector of edge weights; `NULL` counts edges.
#' @param directed Logical; if `TRUE` only traverse edges child-to-parent.
#' @return Numeric matrix of geodesic distances (sources in rows, targets in
#'   columns).
#' @export
geodesic_distances <- function(parents, sources, targets, weights, directed) .Call(wrap__geodesic_distances, parents, sources, targets, weights, directed)

#' Calculate Strahler Index.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param greedy Logical; use the greedy variant of the algorithm.
#' @param to_ignore Optional integer vector of node indices to skip.
#' @param min_twig_size Optional integer; ignore twigs shorter than this.
#' @return Integer vector with the Strahler index of each node.
#' @export
strahler_index <- function(parents, greedy, to_ignore, min_twig_size) .Call(wrap__strahler_index, parents, greedy, to_ignore, min_twig_size)

#' Connected components.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @return Integer vector assigning each node a component id.
#' @export
connected_components <- function(parents) .Call(wrap__connected_components, parents)

#' Prune twigs below given threshold.
#'
#' Returns indices of nodes to keep.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param threshold Numeric length threshold; twigs shorter than this are pruned.
#' @param weights Optional numeric vector of edge weights; `NULL` counts edges.
#' @return Integer vector of node indices to keep.
#' @export
prune_twigs <- function(parents, threshold, weights) .Call(wrap__prune_twigs, parents, threshold, weights)

#' Calculate child -> parent distances.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param x,y,z Numeric vectors of node coordinates, one entry per node.
#' @return Numeric vector of Euclidean child-to-parent distances (`0` for roots).
#' @export
child_to_parent_dists <- function(parents, x, y, z) .Call(wrap__child_to_parent_dists, parents, x, y, z)

#' Return path length from a single node to the root.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param node Integer index of the node to measure from.
#' @return Numeric path length (edge count) from `node` to its root.
#' @export
dist_to_root <- function(parents, node) .Call(wrap__dist_to_root, parents, node)

#' Classify nodes into roots (0), leaves (1), branch points (2) and slabs (3).
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @return Integer vector: `0` root, `1` leaf, `2` branch point, `3` slab.
#' @export
classify_nodes <- function(parents) .Call(wrap__classify_nodes, parents)

#' Check whether the tree contains cycles.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @return Logical; `TRUE` if the parent structure contains a cycle.
#' @export
has_cycles <- function(parents) .Call(wrap__has_cycles, parents)

#' Geodesic distances for explicit pairs of nodes.
#'
#' `sources` and `targets` are parallel arrays of node indices; the returned
#' vector holds the distance between each `(source, target)` pair.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param sources Integer vector of source node indices.
#' @param targets Integer vector of target node indices (same length as
#'   `sources`).
#' @param weights Optional numeric vector of edge weights; `NULL` counts edges.
#' @param directed Logical; if `TRUE` only traverse edges child-to-parent.
#' @return Numeric vector with the distance of each `(source, target)` pair.
#' @export
geodesic_pairs <- function(parents, sources, targets, weights, directed) .Call(wrap__geodesic_pairs, parents, sources, targets, weights, directed)

#' Distance to the nearest target for each source.
#'
#' Memory-efficient companion to `geodesic_distances` that never materialises the
#' full distance matrix. Returns a list with `distances` (distance to the nearest
#' target) and `nearest` (index of that target); sources without a reachable
#' target get `-1`.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param sources Optional integer vector of source node indices; `NULL` uses
#'   every node.
#' @param targets Optional integer vector of target node indices; `NULL` uses
#'   every node.
#' @param weights Optional numeric vector of edge weights; `NULL` counts edges.
#' @param directed Logical; if `TRUE` only traverse edges child-to-parent.
#' @return List with `distances` (numeric, distance to the nearest target) and
#'   `nearest` (integer target index, `-1` when unreachable).
#' @export
geodesic_nearest <- function(parents, sources, targets, weights, directed) .Call(wrap__geodesic_nearest, parents, sources, targets, weights, directed)

#' Distance to the farthest target for each source.
#'
#' The mirror image of `geodesic_nearest`: same linear-time algorithm, but it keeps
#' the farthest rather than the nearest target and never materialises the full
#' distance matrix. Returns a list with `distances` (distance to the farthest
#' target) and `farthest` (index of that target); sources without a reachable
#' target get `-1`. A source that is itself a target is matched to the farthest
#' *other* target, never to itself.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param sources Optional integer vector of source node indices; `NULL` uses
#'   every node.
#' @param targets Optional integer vector of target node indices; `NULL` uses
#'   every node.
#' @param weights Optional numeric vector of edge weights; `NULL` counts edges.
#' @param directed Logical; if `TRUE` only traverse edges child-to-parent. With
#'   non-negative weights the farthest such target is the target ancestor closest
#'   to the root.
#' @return List with `distances` (numeric, distance to the farthest target) and
#'   `farthest` (integer target index, `-1` when unreachable).
#' @export
geodesic_farthest <- function(parents, sources, targets, weights, directed) .Call(wrap__geodesic_farthest, parents, sources, targets, weights, directed)

#' Synapse flow centrality for each node.
#'
#' `presynapses`/`postsynapses` give the number of pre-/post-synapses at each node.
#' `mode` is one of "centrifugal", "centripetal" or "sum".
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param presynapses Integer vector: number of presynapses at each node.
#' @param postsynapses Integer vector: number of postsynapses at each node.
#' @param mode Character; one of `"centrifugal"`, `"centripetal"` or `"sum"`.
#' @return Integer vector with the synapse flow centrality of each node.
#' @export
synapse_flow_centrality <- function(parents, presynapses, postsynapses, mode) .Call(wrap__synapse_flow_centrality, parents, presynapses, postsynapses, mode)

#' Generate linear segments while maximising segment lengths.
#'
#' Returns a list with `segments` (a list of integer vectors, one per segment)
#' and `lengths` (per-segment lengths, or NULL if no weights were supplied).
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param weights Optional numeric vector of edge weights; `NULL` returns no
#'   `lengths`.
#' @return List with `segments` (list of integer node-index vectors) and
#'   `lengths` (numeric per-segment lengths, or `NULL`).
#' @export
generate_segments <- function(parents, weights) .Call(wrap__generate_segments, parents, weights)

#' Break the tree into its linear segments (one integer vector per segment).
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @return List of integer vectors, one per linear segment.
#' @export
break_segments <- function(parents) .Call(wrap__break_segments, parents)

#' Find the minimal-length edges that reconnect the fragments of a skeleton.
#'
#' Given a per-node component label and node coordinates, this returns the set of
#' new edges that would join the fragments into a single tree while minimising the
#' total added length (a minimum spanning tree over the fragments). It does *not*
#' modify the skeleton — see `heal_skeleton` for the one-shot version.
#'
#' @param components Integer vector giving each node's connected component, e.g.
#'   the output of `connected_components()`. Only equality of labels matters.
#' @param x,y,z Numeric vectors of node coordinates, one entry per node.
#' @param w Optional numeric vector giving a 4th coordinate, one entry per node.
#'   The search then happens in 4D, so nodes with similar `w` look closer
#'   together; pass a (scaled) radius here to prefer bridging fragments of
#'   similar calibre. Note that `max_dist` is then measured in 4D too. `NULL`
#'   searches in plain 3D.
#' @param mask Optional logical vector marking the nodes that may be used as
#'   endpoints for a new edge; `NULL` allows every node. A fragment without a
#'   single eligible node cannot be connected.
#' @param max_dist Optional numeric upper bound on the length of any single new
#'   edge; `NULL` means no limit. Fragments whose closest eligible nodes are
#'   farther apart than this are left disconnected.
#' @return List with `from` and `to` (integer vectors of 0-based node indices, one
#'   pair per new edge) and `dist` (numeric edge lengths). At most
#'   `(#fragments - 1)` edges.
#' @export
stitch_fragments <- function(components, x, y, z, w, mask, max_dist) .Call(wrap__stitch_fragments, components, x, y, z, w, mask, max_dist)

#' Regenerate a parent vector after adding a set of undirected edges.
#'
#' Turns an edited edge set back into a valid rooted tree: the undirected
#' adjacency is built from the original child -> parent edges plus the new
#' `from`/`to` edges, then oriented away from `root` by breadth-first search.
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`).
#' @param from,to Integer vectors of 0-based node indices giving the undirected
#'   edges to add, e.g. the `from`/`to` returned by `stitch_fragments()`.
#' @param root Integer 0-based index of the preferred root; its whole component is
#'   rooted there. Use a negative value to auto-pick (lowest index per component).
#' @return Integer vector of new 0-based parent indices (roots are `-1`). Any
#'   component not reachable from `root` is rooted at its lowest-index node, so the
#'   result is valid even when the skeleton could not be fully healed.
#' @export
reroot_rewire <- function(parents, from, to, root) .Call(wrap__reroot_rewire, parents, from, to, root)

#' Heal a fragmented skeleton by reconnecting its fragments.
#'
#' Convenience wrapper that finds the minimal-length set of new edges between the
#' skeleton's connected components (see `stitch_fragments()`) and regenerates a
#' single rooted tree from them (see `reroot_rewire()`).
#'
#' @param parents Integer vector of 0-based parent indices (roots are `< 0`), e.g.
#'   from `node_indices()`.
#' @param x,y,z Numeric vectors of node coordinates, one entry per node.
#' @param method Character; `"ALL"` lets any node form a new edge, `"LEAFS"`
#'   restricts new edges to leaf and root nodes (faster, occasionally suboptimal
#'   attachment points).
#' @param max_dist Optional numeric maximum length for any single new edge; gaps
#'   larger than this are left unhealed, so the result may stay fragmented. `NULL`
#'   means no limit.
#' @param min_size Optional integer; fragments with fewer than this many nodes are
#'   excluded from healing and stay disconnected. `NULL` heals every fragment.
#' @param mask Optional logical vector restricting which nodes may be used as
#'   endpoints for a new edge; combined with `method`. `NULL` allows every node.
#' @param radius Optional numeric vector of node radii, one entry per node. Only
#'   required when `use_radius` is set.
#' @param use_radius `TRUE`/`FALSE`, a number, or `NULL`. If set, node radii are
#'   taken into account when measuring distances, which prioritises connecting
#'   fragments of similar calibre. A number weights the effect: higher values give
#'   radius more influence (`TRUE` means 1). To keep this robust we use the mean
#'   radius of the segment a node belongs to, not the node's own radius. Note that
#'   `max_dist` is then measured in this augmented space too.
#' @return Integer vector of new 0-based parent indices (roots are `-1`). If the
#'   skeleton could be fully healed this is a single tree with one root.
#' @export
heal_skeleton <- function(parents, x, y, z, method, max_dist, min_size, mask, radius, use_radius) .Call(wrap__heal_skeleton, parents, x, y, z, method, max_dist, min_size, mask, radius, use_radius)

#' Find connected components of a triangle mesh.
#'
#' `faces` is an (N, 3) matrix of vertex indices. Returns an integer vector of
#' length `n_vertices` assigning each vertex the root-vertex index of its
#' component.
#'
#' @param faces Integer or numeric `(N, 3)` matrix of triangle vertex indices.
#' @param n_vertices Integer; total number of vertices in the mesh.
#' @return Integer vector of length `n_vertices` giving each vertex the
#'   root-vertex index of its component.
#' @export
mesh_connected_components <- function(faces, n_vertices) .Call(wrap__mesh_connected_components, faces, n_vertices)

#' Geodesic ("along-the-mesh-edge") distances on a triangle mesh.
#'
#' The mesh counterpart to `geodesic_distances`, which works on skeletons. A
#' skeleton is a tree, so distances there come from walking to the lowest common
#' ancestor; a mesh is a general cyclic graph, so this runs one Dijkstra per source
#' (or a BFS when unweighted), in parallel.
#'
#' Note this is the distance *along mesh edges*, not the exact surface geodesic:
#' paths are constrained to run along edges, so on a coarse mesh they overshoot.
#'
#' Beware the size of the output: a full `V x V` matrix is ~107 GB at V = 164k. Use
#' `sources` and/or `targets` — unlike `scipy`'s Dijkstra, passing `targets` here
#' means only those columns are ever allocated.
#'
#' @param faces Integer or numeric `(F, 3)` matrix of triangle vertex indices
#'   (0-based).
#' @param n_vertices Integer; total number of vertices in the mesh.
#' @param vertices Optional numeric `(V, 3)` matrix of vertex coordinates. If
#'   given, edges are weighted by their euclidean length; if `NULL`, every edge has
#'   weight 1 and the result is a hop count.
#' @param sources Optional integer vector of source vertex indices; `NULL` uses
#'   every vertex.
#' @param targets Optional integer vector of target vertex indices; `NULL` uses
#'   every vertex.
#' @param limit Optional numeric; ignore vertices further away than this.
#' @param threads Optional integer; number of threads. `NULL` uses all cores.
#' @return Numeric matrix of geodesic distances (sources in rows, targets in
#'   columns). Unreachable pairs are `-1`.
#' @export
geodesic_matrix_mesh <- function(faces, n_vertices, vertices, sources, targets, limit, threads) .Call(wrap__geodesic_matrix_mesh, faces, n_vertices, vertices, sources, targets, limit, threads)

#' Geodesic distances over an arbitrary graph given as an edge list.
#'
#' The general form of `geodesic_matrix_mesh`. Unlike `geodesic_distances`, this
#' makes no tree assumption — cycles are fine.
#'
#' @param edges Integer or numeric `(E, 2)` matrix of edges (0-based node indices).
#' @param n_nodes Integer; total number of nodes.
#' @param weights Optional numeric vector with one length per edge; `NULL` counts
#'   edges. Must be finite and non-negative. Parallel edges collapse to the
#'   shortest.
#' @param directed Logical; if `TRUE` an edge `(u, v)` may only be traversed from
#'   `u` to `v`.
#' @param sources Optional integer vector of source node indices; `NULL` uses every
#'   node.
#' @param targets Optional integer vector of target node indices; `NULL` uses every
#'   node.
#' @param limit Optional numeric; ignore nodes further away than this.
#' @param threads Optional integer; number of threads. `NULL` uses all cores.
#' @return Numeric matrix of geodesic distances (sources in rows, targets in
#'   columns). Unreachable pairs are `-1`.
#' @export
geodesic_matrix_graph <- function(edges, n_nodes, weights, directed, sources, targets, limit, threads) .Call(wrap__geodesic_matrix_graph, edges, n_nodes, weights, directed, sources, targets, limit, threads)

#' Distance to the nearest target vertex, for each source vertex of a mesh.
#'
#' A memory-efficient alternative to `geodesic_matrix_mesh`: it keeps only the
#' nearest target and the distance to it, so the output is `O(sources)` rather than
#' `O(sources * targets)`. It is also faster, because the search stops at the first
#' target it settles rather than exploring the whole component.
#'
#' Returns a list with `distances` and `nearest` (the vertex index of that nearest
#' target). Sources with no reachable target get `-1`. A source that is itself a
#' target is matched to its nearest *other* target, never to itself.
#'
#' @param faces Integer or numeric `(F, 3)` matrix of triangle vertex indices.
#' @param n_vertices Integer; total number of vertices in the mesh.
#' @param vertices Optional numeric `(V, 3)` matrix of vertex coordinates; `NULL`
#'   counts edges.
#' @param sources Optional integer vector of source vertex indices; `NULL` uses
#'   every vertex.
#' @param targets Optional integer vector of target vertex indices; `NULL` uses
#'   every vertex.
#' @param limit Optional numeric; ignore targets further away than this.
#' @param threads Optional integer; number of threads. `NULL` uses all cores.
#' @return A list with `distances` and `nearest`.
#' @export
geodesic_nearest_mesh <- function(faces, n_vertices, vertices, sources, targets, limit, threads) .Call(wrap__geodesic_nearest_mesh, faces, n_vertices, vertices, sources, targets, limit, threads)

#' Distance to the farthest target vertex, for each source vertex of a mesh.
#'
#' The mirror image of `geodesic_nearest_mesh`, with the same `O(sources)` memory
#' footprint. Unlike `nearest`, this cannot stop early — it has to settle every
#' target — but the farthest one then comes for free, because the search settles
#' vertices in increasing order of distance.
#'
#' Returns a list with `distances` and `farthest`. Sources with no reachable target
#' get `-1`. A source that is itself a target is matched to a *distinct* target.
#'
#' @param faces Integer or numeric `(F, 3)` matrix of triangle vertex indices.
#' @param n_vertices Integer; total number of vertices in the mesh.
#' @param vertices Optional numeric `(V, 3)` matrix of vertex coordinates; `NULL`
#'   counts edges.
#' @param sources Optional integer vector of source vertex indices; `NULL` uses
#'   every vertex.
#' @param targets Optional integer vector of target vertex indices; `NULL` uses
#'   every vertex.
#' @param limit Optional numeric; ignore targets further away than this.
#' @param threads Optional integer; number of threads. `NULL` uses all cores.
#' @return A list with `distances` and `farthest`.
#' @export
geodesic_farthest_mesh <- function(faces, n_vertices, vertices, sources, targets, limit, threads) .Call(wrap__geodesic_farthest_mesh, faces, n_vertices, vertices, sources, targets, limit, threads)

#' The `limit_dist="auto"` value for a scoring matrix.
#'
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param use_alpha Logical; when falling back to the built-in matrix, use the
#'   alpha-weighted variant.
#' @return Numeric `limit_dist` value implied by the scoring matrix.
#' @export
smat_auto_limit <- function(smat_values, dist_edges, dot_edges, use_alpha) .Call(wrap__smat_auto_limit, smat_values, dist_edges, dot_edges, use_alpha)

#' All-by-all forward NBLAST.
#'
#' `points`/`vects` are lists of (N, 3) matrices (one per neuron). Returns an
#' (n, n) score matrix; cell (i, j) is query i against target j.
#'
#' @param points List of `(N, 3)` numeric matrices of neuron point coordinates.
#' @param vects List of `(N, 3)` numeric matrices of unit tangent vectors, one
#'   per neuron and aligned with `points`.
#' @param alphas Optional list of per-point alpha (anisotropy) vectors; `NULL`
#'   disables alpha weighting.
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param normalize Logical; normalise each score by the query self-match score.
#' @param limit_dist Optional numeric distance cut-off; `NULL` disables it.
#' @param n_cores Optional integer thread count; `NULL` or `<= 0` uses all cores.
#' @param precision Integer; compute in 32- or 64-bit floats.
#' @param progress Logical; display a progress bar.
#' @return Numeric `(n, n)` score matrix; cell `(i, j)` is query `i` vs target `j`.
#' @export
nblast_allbyall <- function(points, vects, alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress) .Call(wrap__nblast_allbyall, points, vects, alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress)

#' Forward NBLAST of every query neuron against every target neuron.
#'
#' Returns an (n_query, n_target) score matrix.
#'
#' @param q_points List of `(N, 3)` numeric matrices of query point coordinates.
#' @param q_vects List of `(N, 3)` numeric matrices of query tangent vectors.
#' @param t_points List of `(N, 3)` numeric matrices of target point coordinates.
#' @param t_vects List of `(N, 3)` numeric matrices of target tangent vectors.
#' @param q_alphas Optional list of per-point alpha vectors for the queries;
#'   `NULL` disables alpha weighting.
#' @param t_alphas Optional list of per-point alpha vectors for the targets.
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param normalize Logical; normalise each score by the query self-match score.
#' @param limit_dist Optional numeric distance cut-off; `NULL` disables it.
#' @param n_cores Optional integer thread count; `NULL` or `<= 0` uses all cores.
#' @param precision Integer; compute in 32- or 64-bit floats.
#' @param progress Logical; display a progress bar.
#' @return Numeric `(n_query, n_target)` score matrix.
#' @export
nblast <- function(q_points, q_vects, t_points, t_vects, q_alphas, t_alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress) .Call(wrap__nblast, q_points, q_vects, t_points, t_vects, q_alphas, t_alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress)

#' Forward NBLAST for a set of `(query, target)` index pairs.
#'
#' `q_idx`/`t_idx` are 0-based indices into the query/target lists; element k of
#' the result is query `q_idx[k]` against target `t_idx[k]`.
#'
#' @param q_points List of `(N, 3)` numeric matrices of query point coordinates.
#' @param q_vects List of `(N, 3)` numeric matrices of query tangent vectors.
#' @param t_points List of `(N, 3)` numeric matrices of target point coordinates.
#' @param t_vects List of `(N, 3)` numeric matrices of target tangent vectors.
#' @param q_idx Integer vector of 0-based query indices, one per pair.
#' @param t_idx Integer vector of 0-based target indices (same length as `q_idx`).
#' @param q_alphas Optional list of per-point alpha vectors for the queries;
#'   `NULL` disables alpha weighting.
#' @param t_alphas Optional list of per-point alpha vectors for the targets.
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param normalize Logical; normalise each score by the query self-match score.
#' @param limit_dist Optional numeric distance cut-off; `NULL` disables it.
#' @param n_cores Optional integer thread count; `NULL` or `<= 0` uses all cores.
#' @param precision Integer; compute in 32- or 64-bit floats.
#' @param progress Logical; display a progress bar.
#' @return Numeric vector of scores, one per `(query, target)` pair.
#' @export
nblast_pairs <- function(q_points, q_vects, t_points, t_vects, q_idx, t_idx, q_alphas, t_alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress) .Call(wrap__nblast_pairs, q_points, q_vects, t_points, t_vects, q_idx, t_idx, q_alphas, t_alphas, smat_values, dist_edges, dot_edges, normalize, limit_dist, n_cores, precision, progress)

#' All-by-all forward syNBLAST over synapse clouds.
#'
#' `points` are lists of (N, 3) connector coordinate matrices and `types` the
#' matching per-connector integer type ids. Returns an (n, n) score matrix.
#'
#' @param points List of `(N, 3)` numeric matrices of connector coordinates,
#'   one per neuron.
#' @param types List of integer vectors of per-connector type ids, aligned with
#'   `points`.
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param normalize Logical; normalise each score by the query self-match score.
#' @param n_cores Optional integer thread count; `NULL` or `<= 0` uses all cores.
#' @param precision Integer; compute in 32- or 64-bit floats.
#' @param progress Logical; display a progress bar.
#' @return Numeric `(n, n)` score matrix; cell `(i, j)` is query `i` vs target `j`.
#' @export
synblast_allbyall <- function(points, types, smat_values, dist_edges, dot_edges, normalize, n_cores, precision, progress) .Call(wrap__synblast_allbyall, points, types, smat_values, dist_edges, dot_edges, normalize, n_cores, precision, progress)

#' Forward syNBLAST of every query neuron against every target neuron.
#'
#' Returns an (n_query, n_target) score matrix.
#'
#' @param q_points List of `(N, 3)` numeric matrices of query connector
#'   coordinates.
#' @param q_types List of integer vectors of query per-connector type ids.
#' @param t_points List of `(N, 3)` numeric matrices of target connector
#'   coordinates.
#' @param t_types List of integer vectors of target per-connector type ids.
#' @param smat_values Numeric scoring matrix, or `NULL` for the built-in FCWB
#'   matrix.
#' @param dist_edges Numeric vector of distance bin edges for `smat_values`.
#' @param dot_edges Numeric vector of dot-product bin edges for `smat_values`.
#' @param normalize Logical; normalise each score by the query self-match score.
#' @param n_cores Optional integer thread count; `NULL` or `<= 0` uses all cores.
#' @param precision Integer; compute in 32- or 64-bit floats.
#' @param progress Logical; display a progress bar.
#' @return Numeric `(n_query, n_target)` score matrix.
#' @export
synblast <- function(q_points, q_types, t_points, t_types, smat_values, dist_edges, dot_edges, normalize, n_cores, precision, progress) .Call(wrap__synblast, q_points, q_types, t_points, t_types, smat_values, dist_edges, dot_edges, normalize, n_cores, precision, progress)


# nolint end
