name: test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

defaults:
 run:
  working-directory: ./py

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build and install fastcore
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
          working-directory: py
      - name: Run tests
        run: |
          pip install pytest
          pytest