name: test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

defaults:
 run:
  working-directory: ./py

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out $TGT_DIR
          sccache: 'true'
          manylinux: auto
          working-directory: py
        env:
          TGT_DIR: "target/wheels/${{ matrix.python-version }}"
      - name: Install package
        run: |
          pip install $TGT_DIR/*.whl
        env:
          TGT_DIR: "target/wheels/${{ matrix.python-version }}"
      - name: Run tests
        run: |
          pip install pytest pandas scipy
          pytest